modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "abitmorehex"
version = "${version}"
displayName = "ABitMoreHex: Recasted"
logoFile = "assets/abitmorehex/icon.png"
authors = "aBit"
description = "ABitMoreHex: Recasted addon for Hex Casting"

[[dependencies.abitmorehex]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abitmorehex]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abitmorehex]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abitmorehex]]
modId = "cloth_config"
mandatory = true
versionRange = "[${versions.cloth_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abitmorehex]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting_dependency},)"
ordering = "NONE"
side = "BOTH"
