# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v0.2.0
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
advanced: true
capitalize_platforms: true
classname: Abitmorehex
generate_vscode: false
github_repo: aBitMoreHexcasting
github_user: WillowWLJPearl
gradle_deps_type: gradle/libs.versions.toml
gradle_hex_version_key: hexcasting
gradle_mod_version_key: modVersion
main_branch: 1.20.1
minecraft_version: 1.20.1
minecraft_version_in_mod_version: false
mod_description: 'Abitmorehex: Recasted addon for Hex Casting.'
mod_display_name: 'Abitmorehex: Recasted'
modid: abitmorehex
multiloader: true
package_name: hexdoc-abitmorehex
package_slug: hexdoc_abitmorehex
pages_url: https://willowwljpearl.github.io/aBitMoreHexcasting
pattern_registry_path: main/kotlin/net/abit/abitmorehex/registry/AbitmorehexActions.kt
source_url: https://github.com/WillowWLJPearl/aBitMoreHexcasting
