# non-minecraft values
org.gradle.jvmargs=-Xmx2048M
jetbrainsAnnotationsVersion=23.0.0
# gradle kotlin jvm plugin breaks without this
kotlin.stdlib.default.dependency=false
# needed for mixins to work for forge
asmVersion=9.4
# mod info
modID=abitmorehex
modVersion=1.0.2
mavenGroup=net.abitmorehex
# publishing
curseforgeId=1122270
modrinthId=
# core
minecraftVersion=1.20.1
yarnMappingsVersion=1.20.1+build.10:v2
enabledPlatforms=fabric,forge
fabricLoaderVersion=0.14.21
fabricApiVersion=0.85.0+1.20.1
fabricKotlinVersion=1.9.4+kotlin.1.8.21
forgeVersion=1.20.1-47.3.0
forgeKotlinVersion=4.3.0
architecturyVersion=9.2.14
# hex casting
hexcastingVersion=0.11.2-pre-702
paucalVersion=0.6.0-pre-118
patchouliVersion=84
cardinalComponentsVersion=5.2.1
serializationHooksVersion=0.4.27
entityReachVersion=2.4.0
trinketsVersion=3.7.0
inlineVersion=1.0.2
clothConfigVersion=11.1.106

#hexalVersion=0.2.3

loomVersion=1.0-SNAPSHOT